[package]
name = "webui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
validator = { version = "0.19.0", features = ["derive"] }
validator_derive = "0.19.0"
web-sys = "0.3.77"
yew = { version = "0.21.0", features = ["csr"] }
